# Generated by Django 5.1.1 on 2024-10-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_date_appointment_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('rheumatology', 'Rheumatology'), ('family_medicine', 'Family Medicine'), ('internal_medicine', 'Internal Medicine')], default='internal_medicine', max_length=50),
        ),
    ]
